name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - compile # TODO: remove
jobs:
  test:
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.14.1
      - name: test
        run: zig build test
